### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by Ti64CLi** [lights0123/n-link#22]
I'm on Arch Linux and it seems like it's trying to open specific versions of some shared objects, which aren't up to date.
I had to manually create symlink for each of them.
These are the two missing :
libssl.so.1.1 and libcrypto.so.1.1

I also had a missing issue with libwebkit2gtk-4.0.so.37 but installing webkit2gtk-4.1 solved this.

**Comment by myclevorname** [comment]
~bump
I also have the same problem with libssl.so.1.1. The official Deiban package provides no installation candidate, so I emailed the maintainers about it. However, the AppImage still requires the library. I am not sure if that is intentional or not, but it prevents me from using this without having to install Chromium.

OS: Debian 12 AMD64 (x86_64)
Calculator: TI-Nspire CX II CAS

**Comment by lights0123** [comment]
I no longer have time to maintain this project—however, rebuilding it should be as simple as installing Node.js, yarn, and Rust, then following the [build instructions](https://github.com/lights0123/n-link/tree/main/desktop#n-link).

**Comment by rawlingsr** [comment]
I don't think this is building currently.

I think I have all the dependencies, but some of the libraries on which this depends might need to be pulled into the future. I tinkered with `/desktop/src-tauri/cargo.toml`, to to avail.

**Comment by rawlingsr** [comment]
I had another chance to take a look at this, and I got it building, but it looks like more work than I had time for would be needed to keep all current functionality and keep the build process simple. I opened https://github.com/lights0123/n-link/pull/28 so that if anyone else needs to build this locally, they can.

**Comment by AlphaJack** [comment]
I get the following error when running `yarn` and then `yarn tauri:build`:

```js
yarn install v1.22.21
[1/4] Resolving packages...
success Already up-to-date.
Done in 3.23s.
yarn run v1.22.21
$ vue-cli-service tauri:build

⠋  Building for production...(node:34822) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
⠙  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
⠸  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:114
                        throw e;
                        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/cache-loader/dist/index.js:240:7
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/neo-async/async.js:2830:7
    at done (/tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/neo-async/async.js:2865:11)
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/neo-async/async.js:2818:7
    at /tmp/makepkg/n-link/src/n-link-0.1.6/node_modules/cache-loader/dist/index.js:229:9 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.7.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 64BitUniverse** [comment]
From downloading and trying to build this myself, it seems like n-link needs a dependency bump. Problem is, there's a bunch of other custom libraries that lights has made to facilitate connecting to the nspire. The biggest one that's hanging me up is trying to figure out how to update the web-libnspire repo.
